version: '3.8'

services:
  # Replace with your actual service names
  service1:
    build: ./service1
    environment:
      # Database connection details for service1
      DATABASE_HOST: service1-db
      DATABASE_PORT: 5432  # Example port for PostgreSQL
      DATABASE_USER: username
      DATABASE_PASSWORD: password
    ports:
      - "8080:8080"  # Example port mapping for service1

  service2:
    build: ./service2
    environment:
      # Database connection details for service2
      DATABASE_HOST: service2-db
      DATABASE_PORT: 5432  # Example port for PostgreSQL
      DATABASE_USER: username
      DATABASE_PASSWORD: password
    ports:
      - "8081:8081"  # Example port mapping for service2

  # ... (other service definitions)

  # Database services (optional, adjust based on your database choice)
  service1-db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: password  # Set a strong password
    volumes:
      - service1-db-data:/var/lib/postgresql/data  # Persistent data volume (optional)

  service2-db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: password  # Set a strong password
    volumes:
      - service2-db-data:/var/lib/postgresql/data  # Persistent data volume (optional)

# ... (other database service definitions if needed)

volumes:
  # Volumes for persistent database data (optional)
  service1-db-data: {}
  service2-db-data: {}

