apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
spec:
  replicas: 1  # Adjust the number of replicas as needed
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
      - name: auth-service
        image: auth-svc-5.0.0  # Update with your image location if different
        ports:
        - containerPort: 50051
        envFrom:
        - secretRef:
            name: auth-service-db-credentials  # Reference a ConfigMap for .env vars
            
        volumeMounts:
        - name: app-env  # Mount the .env file volume
      volumes:
      - name: app-env
        configMap:
          name: auth-service-env  # Reference the ConfigMap
      dependsOn:
      - name: postgres-auth
      - name: rabbitmq
      restartPolicy: Always
      networks:
      - auth-network
      - rabbitmq-network
---

apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  selector:
    app: auth-service
  ports:
  - port: 50051
    targetPort: 50051
    protocol: TCP
  type: ClusterIP  # Adjust type if needed (e.g., LoadBalancer)
  networks:
  - auth-network

---

# Optional ConfigMap for .env (replace with actual name)
apiVersion: v1
kind: ConfigMap
metadata:
  name: .env
data:
  # ... Your environment variables unrelated to credentials ...  

---

# Secret for service-specific env vars (including credentials)
apiVersion: v1
kind: Secret
metadata:
  name: auth-service-env
stringData:
  DATABASE_URL: postgres://${AUTH_SERVICE_DB_USER}:${AUTH_SERVICE_DB_PASSWORD}@postgres-auth:5432/${AUTH_SERVICE_DB_NAME}
  RABBITMQ_URL: amqp://${RABBITMQ_DEFAULT_USER}:${RABBITMQ_DEFAULT_PASS}@rabbitmq:5672/

---
apiVersion: v1
kind: Secret
metadata:
  name: auth-service-db-credentials
stringData:
  POSTGRES_USERNAME: ${AUTH_SERVICE_DB_USER}
  POSTGRES_PASSWORD: ${AUTH_SERVICE_DB_PASSWORD}
  POSTGRES_HOST: ${POSTGRES_AUTH_HOST}  # Replace with actual database host
  POSTGRES_DB: ${AUTH_SERVICE_DB_NAME}  # Replace with actual database name
